"""
Reusable draw.io (mxGraph) flowchart generator library.

Usage pattern (see SKILL.md for the full workflow):

    import importlib.util, sys
    spec = importlib.util.spec_from_file_location("drawio_gen", ".claude/skills/drawio-flowchart/drawio_gen.py")
    dg = importlib.util.module_from_spec(spec); spec.loader.exec_module(dg)

    nodes = [
        dg.n('start', '開始', 'start', x=380, y=0, w=160, h=50),
        dg.n('p1', '做某件事', 'process', x=340, y=90),
        dg.n('d1', '條件成立?', 'decision', x=340, y=190, h=90),
        dg.n('errX', 'ERR_CODE\n錯誤說明', 'error', x=620, y=200, w=200),
        dg.n('end', '結束', 'end', x=350, y=320, w=200, h=50),
    ]
    edges = [
        dg.e('start', 'p1'), dg.e('p1', 'd1'),
        dg.e('d1', 'errX', '否'), dg.e('d1', 'end', '是'),
    ]
    xml = dg.build('我的流程', nodes, edges, page_w=900, page_h=500)
    open('output.drawio', 'w', encoding='utf-8').write(xml)

Node types and their meaning (pick the one that matches the spec's semantics,
don't invent new ones without adding a STYLES entry):
    start / end   - ellipse, green          -> flow entry/exit points
    process       - rectangle, blue         -> a single step / API call / state change
    decision      - rhombus, yellow         -> a branch described in the spec as "X 成立?" / "Y 有效?"
    error         - rounded rect, red       -> a terminal error-code outcome (labelled "<CODE>\n<message>")
    note          - dashed rounded rect     -> a non-blocking annotation (background/async behavior, cross-refs)

CRITICAL GOTCHA: edge ids are auto-generated by build() as "e0", "e1", "e2", ...
Never give a node an id matching that pattern (e.g. 'e1') - it will collide with
an edge id in the same file and silently corrupt the diagram (duplicate mxCell id).
Use a distinct prefix for error/annotation node ids instead, e.g. 'err1', 'errAuth', 'noteWeb'.

BEFORE WRITING THE FILE, always call check_overlaps(nodes, edges) - a structurally valid
file can still render with lines drawn straight over other nodes' text. If it flags an edge,
either widen the spacing between whatever it's crossing, or give that edge explicit waypoints:
dg.e(src, dst, label, waypoints=[(x1,y1), (x2,y2), ...]) forces the exact polyline instead of
leaving it to mxGraph's auto-router. See SKILL.md "Routing edges around obstacles" for the
corridor/bus pattern used when several edges need to thread past the same obstacles.
"""
import html

STYLES = {
    'start':    'ellipse;whiteSpace=wrap;html=1;fillColor=#d5e8d4;strokeColor=#82b366;fontSize=12;',
    'end':      'ellipse;whiteSpace=wrap;html=1;fillColor=#d5e8d4;strokeColor=#82b366;fontSize=12;',
    'process':  'rounded=0;whiteSpace=wrap;html=1;fillColor=#dae8fc;strokeColor=#6c8ebf;fontSize=12;',
    'decision': 'rhombus;whiteSpace=wrap;html=1;fillColor=#fff2cc;strokeColor=#d6b656;fontSize=12;',
    'error':    'rounded=1;whiteSpace=wrap;html=1;fillColor=#f8cecc;strokeColor=#b85450;fontSize=12;',
    'note':     'rounded=1;whiteSpace=wrap;html=1;fillColor=#f5f5f5;strokeColor=#666666;fontSize=11;dashed=1;',
    # ER / DB-schema diagrams: one box per table, label = table name + field list
    # (plain text, left-aligned, top-aligned) — see build_entity_label() below.
    # Prefer 'table' + 'tablerow' below when the foreign keys should connect to the
    # actual columns; 'entity' can only be connected box-to-box.
    'entity':   'rounded=0;whiteSpace=wrap;html=1;fillColor=#ffffff;strokeColor=#333333;'
                'align=left;verticalAlign=top;fontSize=11;spacingLeft=8;spacingTop=6;',
    # Relational schema diagrams: a table is a swimlane whose children are one cell per
    # column, so an edge can attach to `users.id` rather than to the users box. The
    # column cells declare east/west connection points, which is what makes a foreign
    # key render as a line from one column straight into another.
    'table':    'swimlane;html=1;whiteSpace=wrap;childLayout=stackLayout;horizontal=1;'
                'startSize=40;horizontalStack=0;resizeParent=1;resizeParentMax=0;'
                'collapsible=0;marginBottom=0;fillColor=#ffffff;strokeColor=#333333;'
                'fontSize=13;fontStyle=1;align=center;',
    'tablerow': 'shape=partialRectangle;html=1;whiteSpace=wrap;overflow=hidden;'
                'connectable=1;fillColor=none;strokeColor=#c8ccd4;'
                'top=0;left=0;right=0;bottom=1;align=left;verticalAlign=middle;'
                'spacingLeft=8;spacingRight=8;fontSize=11;fontFamily=Courier New;'
                'points=[[0,0.5,0,0,0],[1,0.5,0,0,0]];portConstraint=eastwest;',
    # System/architecture diagrams: our own components, external third-party services,
    # client apps/devices, and a dashed boundary box for a deployment host (e.g. one VM).
    'component': 'rounded=0;whiteSpace=wrap;html=1;fillColor=#dae8fc;strokeColor=#6c8ebf;fontSize=12;',
    'client':    'rounded=0;whiteSpace=wrap;html=1;fillColor=#e1d5e7;strokeColor=#9673a6;fontSize=12;',
    'external':  'rounded=0;whiteSpace=wrap;html=1;fillColor=#f5f5f5;strokeColor=#666666;fontSize=12;',
    'container': 'rounded=0;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#666666;'
                 'dashed=1;verticalAlign=top;align=center;fontSize=13;fontStyle=1;',
}


def esc(s):
    return html.escape(str(s), quote=True)


def n(id, label, type='process', x=360, y=0, w=200, h=60):
    """Define one flowchart node. id must be unique within the diagram and must
    NOT match the pattern e<digits> (reserved for auto-generated edge ids)."""
    if type not in STYLES:
        raise ValueError(f"unknown node type '{type}', add it to STYLES first")
    return dict(id=id, label=label, type=type, x=x, y=y, w=w, h=h)


def build_entity_label(table_name, fields):
    """Build a plain-text ER table label for an 'entity' node.
    fields: list of (marker, text) where marker is 'PK', 'FK', or '' (blank, aligned)."""
    lines = [table_name, '─' * max(12, len(table_name) * 2)]
    for marker, text in fields:
        prefix = f'{marker:<3}' if marker else '   '
        lines.append(f'{prefix} {text}')
    return '\n'.join(lines)


TABLE_HEADER_H = 40
TABLE_ROW_H = 30


def table(id, name, columns, x, y, w=280, header_h=TABLE_HEADER_H, row_h=TABLE_ROW_H):
    """One relational table: the box plus one child cell per column.

    columns: list of (marker, text) — marker is 'PK', 'FK' or '' (blank, kept aligned).
    Column cell ids are f'{id}.{first word of text}', e.g. 'users.id', so foreign keys
    read naturally at the call site: e('users.id', 'devices.user_id', '1—N').

    Returns [table_node, *column_nodes] — pass them into build() in that order; a child
    must never be emitted before its parent or mxGraph cannot resolve the parent id.
    """
    nodes = [dict(id=id, label=name, type='table', x=x, y=y, w=w,
                  h=header_h + row_h * len(columns), parent='1')]
    for i, (marker, text) in enumerate(columns):
        col = text.split()[0]
        nodes.append(dict(
            id=f'{id}.{col}', label=f'{marker:<3}{text}' if marker else f'   {text}',
            type='tablerow', x=x, y=y + header_h + row_h * i, w=w, h=row_h, parent=id,
        ))
    return nodes


def e(src, dst, label=None, waypoints=None, exit=None, entry=None):
    """Define one edge. label is optional (e.g. '是'/'否', or a condition name).
    waypoints: optional list of (x, y) points the edge must pass through, in order,
    to route it around an obstacle — see check_overlaps() and route_around().
    exit/entry: force the attachment side ('top'/'bottom'/'left'/'right'). Leave them
    None and build() derives the side from the geometry — that's usually right."""
    return dict(src=src, dst=dst, label=label, waypoints=waypoints,
                exit=exit, entry=entry)


def _rect_center(node):
    return node['x'] + node.get('w', 160) / 2, node['y'] + node.get('h', 60) / 2


# Fixed attachment points, as fractions of the node's bounding box. These four are
# the only ones we ever use: on a rectangle each is the midpoint of one side, and on
# a rhombus (decision) the same fraction lands exactly on a corner of the diamond,
# because the diamond is inscribed in the box. So one rule covers both shapes.
#
# Without exitX/entryX in the style, mxGraph uses a *floating* connection: it picks a
# perimeter point per render, which drifts off the side's midpoint and leaves the line
# meeting the shape at an angle (it reads as a gap or a kink). Always pin the anchors.
ANCHORS = {'top': (0.5, 0), 'bottom': (0.5, 1), 'left': (0, 0.5), 'right': (1, 0.5)}

# 錨點只有在「那條邊真的是形狀的邊」時才能沿邊分散。矩形類可以；菱形與橢圓不行——
# 它們只有四個中點碰得到形狀，把錨點挪到 (0.33, 0) 就落在框線外的空白處，
# 箭頭會浮在半空、看起來沒接到任何東西。
# 所以菱形／橢圓的同一側若接了多條線，要改成讓它們接不同的邊（見 SKILL.md），
# 而不是硬把錨點分開。
SPREADABLE = {'process', 'error', 'note', 'entity', 'table', 'tablerow',
              'component', 'client', 'external', 'container'}


def _side_towards(node, point):
    """Which side of `node` faces `point`, comparing against the box's own aspect so
    a wide box prefers top/bottom and a tall one prefers left/right."""
    cx, cy = _rect_center(node)
    dx, dy = point[0] - cx, point[1] - cy
    w, h = node.get('w', 160), node.get('h', 60)
    if abs(dx) * h > abs(dy) * w:
        return 'right' if dx > 0 else 'left'
    return 'bottom' if dy >= 0 else 'top'


def edge_sides(edge, by_id):
    """(exit_side, entry_side) for one edge: the first waypoint decides where the line
    leaves the source, the last one decides where it enters the target."""
    if edge.get('exit') and edge.get('entry'):
        return edge['exit'], edge['entry']
    src, dst = by_id[edge['src']], by_id[edge['dst']]
    if edge['src'] == edge['dst']:
        return edge.get('exit') or 'left', edge.get('entry') or 'top'
    wps = list(edge.get('waypoints') or [])
    out_ref = wps[0] if wps else _rect_center(dst)
    in_ref = wps[-1] if wps else _rect_center(src)
    return (edge.get('exit') or _side_towards(src, out_ref),
            edge.get('entry') or _side_towards(dst, in_ref))


def _segment_intersects_rect(x1, y1, x2, y2, rx, ry, rw, rh):
    """True if the axis-aligned segment (x1,y1)-(x2,y2) crosses into rect (rx,ry,rw,rh).
    Segments produced by our routing are always axis-aligned (horizontal or vertical)."""
    if x1 == x2:  # vertical segment
        if not (rx <= x1 <= rx + rw):
            return False
        lo, hi = sorted((y1, y2))
        return hi >= ry and lo <= ry + rh
    if y1 == y2:  # horizontal segment
        if not (ry <= y1 <= ry + rh):
            return False
        lo, hi = sorted((x1, x2))
        return hi >= rx and lo <= rx + rw
    return False  # diagonal segments shouldn't occur in our orthogonal routing


CONTAINER_LABEL_BAND = 26  # px — roughly where a container's top-aligned title renders


def _obstacle_rect(node, margin):
    """The rectangle an edge must actually avoid for this node's *text* not to be
    crossed. Most node types are opaque boxes, so that's their full geometry. A
    'container' is a hollow boundary box (fillColor=none) whose only text is a
    title strip at the top — edges are expected to cross the rest of it freely
    (that's the point of drawing things inside it), so only that top strip counts."""
    if node['type'] == 'container':
        h = min(node.get('h', 60), CONTAINER_LABEL_BAND)
    else:
        h = node.get('h', 60)
    return (node['x'] - margin, node['y'] - margin, node.get('w', 160) + 2 * margin, h + 2 * margin)


def _path_hits(path, obstacles, margin):
    """path: list of (x,y) points forming a polyline. obstacles: list of node dicts.
    Returns the set of obstacle ids the polyline crosses (expanded by margin)."""
    hits = set()
    for node in obstacles:
        rx, ry, rw, rh = _obstacle_rect(node, margin)
        for i in range(len(path) - 1):
            x1, y1 = path[i]
            x2, y2 = path[i + 1]
            if _segment_intersects_rect(x1, y1, x2, y2, rx, ry, rw, rh):
                hits.add(node['id'])
                break
    return hits


def check_overlaps(nodes, edges, margin=6):
    """Approximate check for edges whose routed path would cross a third node's box
    (which in practice means the line is drawn on top of that node's text).

    For edges WITHOUT explicit waypoints, this tries both natural Manhattan routings
    (horizontal-then-vertical, and vertical-then-horizontal) between source and target
    centers, and only reports a problem if BOTH orientations hit something — i.e. no
    sane auto-router could avoid the obstacle, so it needs explicit waypoints.
    For edges WITH explicit waypoints, it checks the exact path you specified.

    Returns a list of dicts: {edge_index, src, dst, blocked_by: {node_id, ...}}.
    Empty list = safe to build.
    """
    by_id = {node['id']: node for node in nodes}
    problems = []
    for idx, edge in enumerate(edges):
        src = by_id[edge['src']]
        dst = by_id[edge['dst']]
        # 欄位列的線從列的左右緣出發，等於直接離開整張表——把自己的父表
        # （以及父表底下的其他列）算成障礙物只會製造假警報。
        kin = {edge['src'], edge['dst']}
        for nid in (edge['src'], edge['dst']):
            parent = by_id[nid].get('parent', '1')
            if parent != '1':
                kin.add(parent)
                kin.update(n['id'] for n in nodes if n.get('parent') == parent)
        obstacles = [node for node in nodes if node['id'] not in kin]
        sx, sy = _rect_center(src)
        dx, dy = _rect_center(dst)

        if edge.get('waypoints'):
            path = [(sx, sy)] + list(edge['waypoints']) + [(dx, dy)]
            hits = _path_hits(path, obstacles, margin)
            if hits:
                problems.append(dict(edge_index=idx, src=edge['src'], dst=edge['dst'], blocked_by=hits))
            continue

        path_a = [(sx, sy), (dx, sy), (dx, dy)]  # horizontal first
        path_b = [(sx, sy), (sx, dy), (dx, dy)]  # vertical first
        hits_a = _path_hits(path_a, obstacles, margin)
        hits_b = _path_hits(path_b, obstacles, margin)
        if hits_a and hits_b:
            problems.append(dict(
                edge_index=idx, src=edge['src'], dst=edge['dst'],
                blocked_by=hits_a & hits_b or (hits_a | hits_b),
            ))
    return problems


def assign_anchors(nodes, edges):
    """Work out每條邊兩端的實際錨點比例，存進 edge['exit_xy'] / edge['entry_xy']。

    單獨一條邊接某一側時就用該側中點。**同一個節點同一側接了多條邊時，沿那一側平均
    分開**（k 條 → 1/(k+1), 2/(k+1), …）：共用同一個錨點的話，那幾條線會從同一點以
    同一個方向出發，在分岔之前完全重合，看起來就只有一條線。一個欄位連到兩個地方，
    讀者要看得出來是兩條線。

    分配順序依「對面那一端的位置」排，所以線在節點旁邊就不會自己先交叉。
    Idempotent：重複呼叫結果相同。
    """
    by_id = {node['id']: node for node in nodes}
    groups = {}
    for edge in edges:
        exit_side, entry_side = edge_sides(edge, by_id)
        edge['_sides'] = (exit_side, entry_side)
        wps = list(edge.get('waypoints') or [])
        far_out = wps[0] if wps else _rect_center(by_id[edge['dst']])
        far_in = wps[-1] if wps else _rect_center(by_id[edge['src']])
        groups.setdefault((edge['src'], exit_side), []).append((far_out, edge, 'exit'))
        groups.setdefault((edge['dst'], entry_side), []).append((far_in, edge, 'entry'))

    for (node_id, side), members in groups.items():
        vary_y = side in ('left', 'right')
        members.sort(key=lambda m: m[0][1] if vary_y else m[0][0])
        k = len(members)
        spreadable = by_id[node_id]['type'] in SPREADABLE
        for i, (_, edge, which) in enumerate(members):
            fx, fy = ANCHORS[side]
            if k > 1 and spreadable:
                f = (i + 1) / (k + 1)
                fx, fy = (fx, f) if vary_y else (f, fy)
            edge[f'{which}_xy'] = (round(fx, 4), round(fy, 4))
    return edges


def edge_anchor_fracs(edge, by_id):
    """(exit, entry) 的比例座標；沒跑過 assign_anchors 就退回該側中點。"""
    if edge.get('exit_xy') and edge.get('entry_xy'):
        return edge['exit_xy'], edge['entry_xy']
    exit_side, entry_side = edge_sides(edge, by_id)
    return ANCHORS[exit_side], ANCHORS[entry_side]


def anchor_point(node, side_or_frac):
    frac = ANCHORS[side_or_frac] if isinstance(side_or_frac, str) else side_or_frac
    return (node['x'] + node.get('w', 160) * frac[0],
            node['y'] + node.get('h', 60) * frac[1])


def align_waypoints(nodes, edges):
    """Nudge each edge's first/last waypoint onto its anchor's axis, in place.

    A waypoint that shares neither x nor y with the anchor forces mxGraph to add a
    dog-leg right where the line meets the shape. The shift is along one axis only and
    is usually a few px, so run check_overlaps() afterwards — it can, in principle,
    move a line into a node. Call this before build(); build() does not do it for you,
    because silently moving geometry you specified would be surprising.
    """
    by_id = {node['id']: node for node in nodes}
    assign_anchors(nodes, edges)
    for edge in edges:
        wps = list(edge.get('waypoints') or [])
        if not wps:
            continue
        exit_side, entry_side = edge['_sides']
        exit_f, entry_f = edge_anchor_fracs(edge, by_id)
        for idx, node_id, side, frac in ((0, edge['src'], exit_side, exit_f),
                                         (-1, edge['dst'], entry_side, entry_f)):
            ax, ay = anchor_point(by_id[node_id], frac)
            px, py = wps[idx]
            if abs(ax - px) <= 0.5 or abs(ay - py) <= 0.5:
                continue
            wps[idx] = (ax, py) if side in ('top', 'bottom') else (px, ay)
        edge['waypoints'] = wps
    return edges


def check_kinks(nodes, edges, tol=0.5):
    """For every edge with waypoints, the anchor and the waypoint next to it must share
    an x or a y. If they don't, mxGraph inserts an extra dog-leg right at the shape —
    which is exactly what "the line doesn't meet the box properly" looks like.

    Returns a list of dicts: {edge_index, src, dst, where: 'exit'|'entry'}.
    Empty list = every line leaves and arrives straight.
    """
    by_id = {node['id']: node for node in nodes}
    assign_anchors(nodes, edges)
    problems = []
    for idx, edge in enumerate(edges):
        wps = list(edge.get('waypoints') or [])
        if not wps:
            continue
        exit_f, entry_f = edge_anchor_fracs(edge, by_id)
        checks = (
            ('exit', anchor_point(by_id[edge['src']], exit_f), wps[0]),
            ('entry', anchor_point(by_id[edge['dst']], entry_f), wps[-1]),
        )
        for where, (ax, ay), (px, py) in checks:
            if abs(ax - px) > tol and abs(ay - py) > tol:
                problems.append(dict(edge_index=idx, src=edge['src'],
                                     dst=edge['dst'], where=where))
    return problems


def build(diagram_name, nodes, edges, page_w=900, page_h=1400):
    """Render nodes/edges into a complete .drawio (mxfile) XML string."""
    node_ids = {node['id'] for node in nodes}
    for i in range(len(edges)):
        pass
    # Fail fast on the classic mistakes rather than emitting a silently broken file.
    seen = set()
    for node in nodes:
        if node['id'] in seen:
            raise ValueError(f"duplicate node id '{node['id']}'")
        seen.add(node['id'])
    for idx, edge in enumerate(edges):
        if edge['src'] not in node_ids:
            raise ValueError(f"edge #{idx} source '{edge['src']}' has no matching node")
        if edge['dst'] not in node_ids:
            raise ValueError(f"edge #{idx} target '{edge['dst']}' has no matching node")

    by_id = {node['id']: node for node in nodes}
    parts = []
    parts.append('<mxfile host="app.diagrams.net">')
    parts.append(f'  <diagram name="{esc(diagram_name)}">')
    parts.append(
        f'    <mxGraphModel dx="800" dy="600" grid="1" gridSize="10" guides="1" '
        f'tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" '
        f'pageWidth="{page_w}" pageHeight="{page_h}" math="0" shadow="0">'
    )
    parts.append('      <root>')
    parts.append('        <mxCell id="0" />')
    parts.append('        <mxCell id="1" parent="0" />')
    for node in nodes:
        style = STYLES[node['type']]
        w = node.get('w', 160)
        h = node.get('h', 60)
        parent = node.get('parent', '1')
        # Node dicts always carry absolute coordinates (every checker here works in
        # absolute space); mxGraph wants a child's geometry relative to its parent.
        x, y = node['x'], node['y']
        if parent != '1':
            p = by_id[parent]
            x, y = x - p['x'], y - p['y']
        parts.append(
            f'        <mxCell id="{esc(node["id"])}" value="{esc(node["label"])}" '
            f'style="{style}" vertex="1" parent="{esc(parent)}">'
        )
        parts.append(f'          <mxGeometry x="{x}" y="{y}" width="{w}" height="{h}" as="geometry" />')
        parts.append('        </mxCell>')
    assign_anchors(nodes, edges)
    for i, edge in enumerate(edges):
        eid = f'e{i}'
        label = edge.get('label')
        val = f' value="{esc(label)}"' if label else ''
        (ex, ey), (nx, ny) = edge_anchor_fracs(edge, by_id)
        style = (
            'edgeStyle=orthogonalEdgeStyle;rounded=0;html=1;fontSize=11;jettySize=auto;'
            f'exitX={ex};exitY={ey};exitDx=0;exitDy=0;'
            f'entryX={nx};entryY={ny};entryDx=0;entryDy=0;'
        )
        parts.append(
            f'        <mxCell id="{eid}"{val} style="{style}" '
            f'edge="1" parent="1" source="{esc(edge["src"])}" target="{esc(edge["dst"])}">'
        )
        waypoints = edge.get('waypoints')
        if waypoints:
            parts.append('          <mxGeometry relative="1" as="geometry">')
            parts.append('            <Array as="points">')
            for wx, wy in waypoints:
                parts.append(f'              <mxPoint x="{wx}" y="{wy}" />')
            parts.append('            </Array>')
            parts.append('          </mxGeometry>')
        else:
            parts.append('          <mxGeometry relative="1" as="geometry" />')
        parts.append('        </mxCell>')
    parts.append('      </root>')
    parts.append('    </mxGraphModel>')
    parts.append('  </diagram>')
    parts.append('</mxfile>')
    return '\n'.join(parts)


def validate_file(path):
    """Post-write sanity check: well-formed XML, no duplicate mxCell ids,
    no edge pointing at a non-existent node. Returns a list of problem strings
    (empty list = clean)."""
    import xml.etree.ElementTree as ET
    problems = []
    try:
        tree = ET.parse(path)
    except ET.ParseError as ex:
        return [f'not well-formed XML: {ex}']
    root = tree.getroot()
    ids = [c.get('id') for c in root.iter('mxCell')]
    dup = {x for x in ids if ids.count(x) > 1}
    if dup:
        problems.append(f'duplicate mxCell ids: {sorted(dup)}')
    node_ids = {c.get('id') for c in root.iter('mxCell') if c.get('vertex') == '1'}
    for c in root.iter('mxCell'):
        if c.get('edge') == '1':
            if c.get('source') not in node_ids:
                problems.append(f"edge {c.get('id')} has dangling source {c.get('source')!r}")
            if c.get('target') not in node_ids:
                problems.append(f"edge {c.get('id')} has dangling target {c.get('target')!r}")
    return problems
